In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [3]:
df = pd.read_csv(path + "/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

#Lower casing

In [4]:
df['review'][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [5]:
df['review'] = df['review'].str.lower()

In [6]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

#Remove html tags

In [7]:
import re

In [8]:
def remove_html_tags(text):
  pattern = re.compile(r"<.*?>")
  return pattern.sub(r'',text)

In [9]:
remove_html_tags(df['review'][3])

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [10]:
df['review'] = df['review'].apply(remove_html_tags)
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

#Remove url

In [11]:
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [12]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.\n\nFor research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.\n\n"

In [13]:
def remove_url(text):
  Pattern = re.compile(r"https?://\S+|www\.S+")
  return Pattern.sub(r'',text)

In [14]:
text1 = remove_html_tags(text1)

In [15]:
text1 = remove_url(text1)
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on  and also watched tutorials at \n\nFor research papers, I visited  and read documentation from  One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out  or  These websites are very helpful for aspiring AI engineers.\n\n"

#Remove punctuation

In [16]:
import string

In [17]:
exclude = string.punctuation

In [18]:
def remove_punch1(text):
  return text.translate(str.maketrans('', '', exclude))

In [19]:
remove_punch1("Hello& This is Rayhan?")

'Hello This is Rayhan'

#Handle special text

In [20]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [21]:
def chat_conversion(text):
  new_text = []

  for w in text.split():
    # print(w)
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)

  return " ".join(new_text)

In [22]:
chat_conversion("LOL ")

'Laughing Out Loud'

In [23]:
chat_conversion("omg!")

'Oh My God'

#Spelling Mistake correction

In [24]:
from textblob import TextBlob

In [25]:
incorrect_text = "bangladeshs is my coubtry"

In [26]:
textblob = TextBlob(incorrect_text)

In [27]:
textblob.correct().string

'bangladeshs is my country'

#Stopwords removal

In [28]:
text = """
Yesterday, I was working on a Machine Learning project in PHITRON, and I was trying to understand how the model is performing on the dataset. The dataset is quite large, and it contains a lot of reviews that are written by users from different countries.

I noticed that the model is not performing well for some of the samples, especially those that are very short or have too many stopwords in them. Because of this, I decided to clean the text data and remove unnecessary words that do not contribute much to the meaning of the sentence.

While I was doing this, I also checked how the preprocessing steps like tokenization, lowercasing, and punctuation removal are affecting the dataset. It was interesting to see that after removing stopwords, the text becomes more meaningful and easier for the model to understand.

In addition to that, I was also reading some documentation from https://scikit-learn.org/stable/ and watching tutorials on https://www.youtube.com while comparing different NLP techniques. The goal is to improve the accuracy of the model and make it more robust for real-world applications.

Overall, I think that removing stopwords is an important step in the NLP pipeline because it helps reduce noise and improve performance of machine learning models.
"""

In [29]:
import nltk

In [30]:
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [33]:
stop_words = set(stopwords.words('english'))

In [36]:
stopwords.words('bengali')

['অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'চেষ্টা',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'ঠিক',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নয়',
 'না',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেই',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'নয়',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিশেষ',
 'বিষয়টি',
 'বেশ',
 'বেশি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুধু',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়']

In [45]:
def remove_stopwords(text):
  words = text.split()
  cleaned = []

  for word in words:
    # print(word)
    word = word.lower().strip(string.punctuation)

    if word and word not in stop_words:
      cleaned.append(word)

  return " ".join(cleaned)

In [46]:
remove_stopwords(text)

'yesterday working machine learning project phitron trying understand model performing dataset dataset quite large contains lot reviews written users different countries noticed model performing well samples especially short many stopwords decided clean text data remove unnecessary words contribute much meaning sentence also checked preprocessing steps like tokenization lowercasing punctuation removal affecting dataset interesting see removing stopwords text becomes meaningful easier model understand addition also reading documentation https://scikit-learn.org/stable watching tutorials https://www.youtube.com comparing different nlp techniques goal improve accuracy model make robust real-world applications overall think removing stopwords important step nlp pipeline helps reduce noise improve performance machine learning models'

In [48]:
df['review'] = df['review'].apply(remove_stopwords)
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy jake think...
4        petter mattei's love time money visually stunn...
                               ...
49995    thought movie right good job creative original...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: object

In [47]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

#Emojies Remove

In [49]:
text_with_emoji = '''Yesterday I completed my Machine Learning project on sentiment analysis 😊🔥.
The model performed really well on the IMDB dataset 👍🎯.
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming 📚💡.
However, debugging errors was quite frustrating 😓💻.
Overall, the experience was amazing and I feel more confident now 🚀😄.'''

In [50]:
def remove_emoji(text):
  emoji_pattern = re.compile(
      "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
  )

  return emoji_pattern.sub(r'', text)

In [52]:
clean_text = remove_emoji(text_with_emoji)
print(clean_text)

Yesterday I completed my Machine Learning project on sentiment analysis .
The model performed really well on the IMDB dataset .
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming .
However, debugging errors was quite frustrating .
Overall, the experience was amazing and I feel more confident now .

#Tokenization

NLTK

In [53]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk

In [54]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [55]:
sent1 = "I am going to CTG"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'CTG']

In [56]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

In [57]:
sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [59]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

Spacy

In [60]:
import spacy

In [61]:
nlp = spacy.load('en_core_web_sm')

In [62]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [66]:
for token in doc3:
  print(token)

A
5
km
ride
cost
$
10.50

#**Stemming**

In [67]:
from nltk.stem.porter import PorterStemmer

In [72]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [73]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [74]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [75]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

#Lemmatization

In [76]:
import nltk
from nltk.stem import  WordNetLemmatizer

In [77]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [80]:
wordnet_lemmatizer = WordNetLemmatizer()
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)

In [81]:
for word in sentence_words:
  if word in punctuations:
    sentence_words.remove(word)

In [82]:
sentence_words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [83]:
print("{0:20}{1:20}".format("Word","Lemma"))

Word                Lemma

In [84]:
for word in sentence_words:
  print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun